### ISSUE TITLE
New Cloudflare Protection VNFM already pushed a fix

Unable to Connect

### ISSUE THREAD

**Issue by LegionInstaller** [GlizzyChief/SillyTavern-1.8.4-fix#1]

**Comment by xEisVogelx** [comment]
That explains why it's not working right now. :(

**Comment by LegionInstaller** [comment]
> That explains why it's not working right now. :(
> 

No worries, a fix should be easy since VFNM already pushed a fix Glizzy just has to edit some Code I think

**Comment by GlizzyChief** [comment]
Hello, dear fellas! The fix provided by VFNM is great, but currently only works on PC (due to running in non-headless mode). I'm currently working on bypassing Cloudflare in headless mode, please hang on tight!

**Comment by xEisVogelx** [comment]
Thank you, I only use the mobile version. Thank you for your effort.

**Comment by LegionInstaller** [comment]
> Hello, dear fellas! The fix provided by VFNM is great, but currently only works on PC (due to running in non-headless mode). I'm currently working on bypassing Cloudflare in headless mode, please hang on tight!

Gigachad

**Comment by recalled0122** [comment]
> Hello, dear fellas! The fix provided by VFNM is great, but currently only works on PC (due to running in non-headless mode). I'm currently working on bypassing Cloudflare in headless mode, please hang on tight!

i love you please marry me

**Comment by GlizzyChief** [comment]
@LegionInstaller @recalled0122 @xEisVogelx  A fix is out! Please check readme and contact me in Discord if you encounter any issues!

**Comment by LegionInstaller** [comment]
> @LegionInstaller @recalled0122 @xEisVogelx  A fix is out! Please check readme and contact me in Discord if you encounter any issues!
> 

Gonna try it out, Thanks Man!

**Comment by Junbolt99** [comment]
I have an question. What does value mean in the step about replacing the 37 line. I'm on termux. Which value are we talking about?.

**Comment by GlizzyChief** [comment]
@Junbolt99 I've made it so that no extra shenanigans are necessary on mobile, so please disregard the file editing part

**Comment by LegionInstaller** [comment]
Problemo Solved

**Comment by recalled0122** [comment]
> @LegionInstaller @recalled0122 @xEisVogelx A fix is out! Please check readme and contact me in Discord if you encounter any issues!

Thank you so much! 🙏🙏🙏 you are doing god's work🙏🙏🙏
