### ISSUE TITLE
Waiting for message is: true
Still generating is: true Loop



### ISSUE THREAD

**Issue by LegionInstaller** [GlizzyChief/SillyTavern-1.8.4-fix#10]
Console logs Waiting for message is: true
Still generating is: true
even after restarting, Poe finishes the message yet ST think it's still generating

**Comment by k3thhw-zz** [comment]
Yees, me too

**Comment by GlizzyChief** [comment]
@LegionInstaller hey, sorry to hear that! Could you please update to the newest version and let me know if the issue persists?

**Comment by GlizzyChief** [comment]
By the way, please don't hesitate to reach out via discord, I'll be able to help faster via it if any issue appears
