### ISSUE TITLE
Poe problem 

### ISSUE THREAD

**Issue by Kethhh** [GlizzyChief/SillyTavern-1.8.4-fix#16]
Hello! Unfortunately, these last few days I'm having problems. the responses don't load at all, I've done everything... I uninstalled termux and installed it again, and nothing works, it appears that the message is being loaded, but then it stops. ;(

**Comment by GlizzyChief** [comment]
Hey, thanks for reaching out, @Kethhh ! Could you please contact me via Discord? My mail client loves not to notify me when a new mail gets sent 😅
