### ISSUE TITLE
 client.checkNumberOfMessages is not a function

### ISSUE THREAD

**Issue by LegionInstaller** [GlizzyChief/SillyTavern-1.8.4-fix#17]
client.checkNumberOfMessages is not a function

Poe does not delete the full stop or any message now

**Comment by GlizzyChief** [comment]
Hmm, very weird, this function shouldn't ever be called in this version of the fix. Is this still present? Checked, and it seems to delete properly as it stands right now

**Comment by LegionInstaller** [comment]
Nope is fine. Works now
