### ISSUE TITLE
Poe

### ISSUE THREAD

**Issue by HakonnokaH** [GlizzyChief/SillyTavern-1.8.4-fix#2]
I just wanted to know if there is any way to fix the poe code, as it seems that SillyTavern is buggy, and no poe works, will this be permanent or will you be able to fix it somehow?

**Comment by LegionInstaller** [comment]
What is your problem ?

**Comment by LegionInstaller** [comment]
> no poe works, even with vpn or other accounts, it's always empty in the part of choosing the CHATGPT option 

Ah then you had the same Issue as me, did you follow the New readme?

**Comment by HakonnokaH** [comment]
not yet

**Comment by GlizzyChief** [comment]
@HakonnokaH please dm me on discord if the issue persists

**Comment by HakonnokaH** [comment]
I already sent you a message on discord yesterday, I'll send you the pictures

**Comment by GlizzyChief** [comment]
Solved via Discord
