### ISSUE TITLE
No Bot Selection Using Poe

### ISSUE THREAD

**Issue by kingofwhinge** [GlizzyChief/SillyTavern-1.8.4-fix#20]
the dropdown menu to select a bot is blank when connected to Poe

**Comment by Kethhh** [comment]
Same for me :((

**Comment by GlizzyChief** [comment]
Hello, thanks for letting me know! I'll put out a patch as soon as I can!

**Comment by Pawel-Dymek** [comment]
yup, same here

**Comment by GlizzyChief** [comment]
Hi @Pawel-Dymek  , forgot to comment on the issue, but the issue should've been resolved already. Could you please run git pull and check again? Thanks!
