### ISSUE TITLE
VelloAI site not loading when SillyTavern tries to connect

### ISSUE THREAD

**Issue by Fewy3** [GlizzyChief/SillyTavern-1.8.4-fix#21]
VelloAI site simply won't load, even reloading page doesn't work.

**Comment by LegendPoet** [comment]
The problem is that the main div with id="root" that contains all the content of the page loads empty. I've been playing with the code and haven't been able to find a solution. Let's hope GlizzyChief can find a way to solve it :')

**Comment by GlizzyChief** [comment]
Hi, sorry for late response! Had notifications off. I'm currently looking into it, will update here once I get some results
