### ISSUE TITLE
Mistral ai invalid or expired token problems

### ISSUE THREAD

**Issue by phongdang9** [GlizzyChief/SillyTavern-1.8.4-fix#22]
![image_2024-08-04_132746853](https://github.com/user-attachments/assets/74b7013c-8cea-4833-8f0e-3dac0ea1c50f)

It said in the cmd that it couldn't get bot name even thought my mistral account connected successfully, i don't know how to fix it, changing accounts didn't works

**Comment by 0101Joe** [comment]
I'm facing the same problem

**Comment by GlizzyChief** [comment]
Hi! It's been fixed, please update to the latest version. They changed some stuff in the UI which caused the errors @phongdang9 @0101Joe

**Comment by 0101Joe** [comment]
It works now. Thank you so much for your efforts!  @GlizzyChief

**Comment by phongdang9** [comment]
Thank you^^
