### ISSUE TITLE
Only chatgpt receiving messages

### ISSUE THREAD

**Issue by IvKir** [GlizzyChief/SillyTavern-1.8.4-fix#4]
So after update 74005b5 i can send messages only to ChatGPT, despite choosing other bots.

**Comment by LegionInstaller** [comment]
Manuell selbst your bot for now

**Comment by IvKir** [comment]
Other issue - is there any way to add extensions to chrome, that used by POE proxy? I need some kind of vpn.

**Comment by GlizzyChief** [comment]
Hello @IvKir, Please update to the newest version for using any custom bots, it's now fixed. And could you please elaborate on the POE proxy thing? Not sure what you mean

**Comment by IvKir** [comment]
Awesome.
Well, POE introduced regional block for my country, so I need to use VPN to access it, but i'd like not to route all of my traffic through it, so maybe there possible way to install extensions for puppeteer chrome?

**Comment by IvKir** [comment]
Nevermind, i found a way to do this. Thanks!

**Comment by LegionInstaller** [comment]
> Awesome.
> Well, POE introduced regional block for my country, so I need to use VPN to access it, but i'd like not to route all of my traffic through it, so maybe there possible way to install extensions for puppeteer chrome? 

Sorry bruv but now everyone has a fucking message limit of 100 per 24 Hours, before in Germany it was Unlimited, so let's just bombard them to remove the limit.

**Comment by IvKir** [comment]
Yeah, but in RU you did not even has that - you just blocked out of bot's alltogether.
