### ISSUE TITLE
Previous Messages get added before New Response

### ISSUE THREAD

**Issue by LegionInstaller** [GlizzyChief/SillyTavern-1.8.4-fix#5]
Right now Previous Messages get added when you Regenerate, No matter how many times I clear the context trough ST or Manually trough Chromium, It will print the previous message and then the new, If I regenerate again after that, I will awnser accordingly

Basically Previous Awnsers from another char get Merged in one text

**Comment by LegionInstaller** [comment]
Edit: Disabling 
Auto-purge API context (save JB) Fixes it

**Comment by LegionInstaller** [comment]
Disabling Steaming did the trick for me

**Comment by GlizzyChief** [comment]
Yeah, streaming is currently buggy on some devices, still a work in progress due to Poe not being compliant) Sorry for the wait!
