### ISSUE TITLE
 TimeoutError: Waiting for selector `.InfiniteScroll_pagingTrigger__Egmr6` failed:

### ISSUE THREAD

**Issue by Sejurni** [GlizzyChief/SillyTavern-1.8.4-fix#7]
Waiting failed: 3000ms exceeded
at Timeout.<anonymous> (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59:37)
-Appears when trying to connect.

**Comment by LegendPoet** [comment]
In my case, this error appeared because your chat history is empty(ie you deleted your chat history in poe), which makes poe redirect pupperet to your profile. Create a new chat directly in poe(for example, say "hello" to ChatGPT), it should solve the problem.

**Comment by Sejurni** [comment]
Thanks for the help, have a good one.
