### ISSUE TITLE
Issues with @puppeteer

### ISSUE THREAD

**Issue by yager54** [GlizzyChief/SillyTavern-1.8.4-fix#8]
I have an invalid/unexpected token prompt that is followed with this error message in this terminal:
![image (1)](https://github.com/GlizzyChief/SillyTavern-1.8.4-fix/assets/138077060/930c30a1-db44-430c-bc82-66f612fd2dc0)
I've been able to use the official Silly Tavern before they stopped supporting POE, so I'm not sure how to resolve this.

**Comment by GlizzyChief** [comment]
Hello! Please do the following to fix this:
1. On your desktop, locate your Chrome shortcut, right click on it and click on "Open file location"
2. In the opened folder, find "chrome.exe". Hold shift and right click on it. In the opened menu, click on "Copy as path"
3. Once you've done this, go to your SillyTavern folder, open src/poe-client.js. On the very first line, you'll see a path to chrome .exe file. Replace it with what you've copied. Also, add an extra \ to each \ in the path you've copied.

Please contact me via discord if you experience difficulties during any of these steps, and I'll gladly help you as soon as I can!

**Comment by GlizzyChief** [comment]
Closed due to inactivity
